### ISSUE TITLE
unclear NextSV issues

### ISSUE THREAD

**Issue by astulaaa** [Nextomics/nextsv#14]
I am running NextSV2 and I get these issues in the log files:

Traceback (most recent call last):
  File "/BiO/Access/home/bioapps/nextsv/nextsv2.py", line 553, in <module>
    main()
  File "/BiO/Access/home/bioapps/nextsv/nextsv2.py", line 128, in main
    check_samtools_version(settings)
  File "/BiO/Access/home/bioapps/nextsv/nextsv2.py", line 254, in check_samtools_version
    results = subprocess.check_output([settings.samtools, "sort"]).decode()
UnicodeDecodeError: 'ascii' codec can't decode byte 0x8b in position 1: ordinal not in range(128)
[12/11/2019 14:33:51] reading config file
unknown parameter: longreadqc

With all this in mind output directories are created but running work.sh does not produce any output in the nextsv_results directory. What could be the reason for these issues, also I wonder why longreadqc parameter is unrecognised?

Thank you

**Comment by kostasgalexiou** [comment]
Hi,

Could someone from the nextsv team reply to the issue addressed by @astulaaa? I run into the same problem.

Regards,
Kostas

**Comment by fangli80** [comment]
Sorry for the late reply. Please check if the `longreadqc` binary file is in the `nextsv/bin/` folder.
