### ISSUE TITLE
AttributeError 

### ISSUE THREAD

**Issue by matbreno** [Nextomics/nextsv#8]
Hi,
I am trying to run nextSV, but I get the following error

```
[12/14/2017 16:58:24] program started
[12/14/2017 16:58:24] reading config file
[12/14/2017 16:58:24] creating output directories
[12/14/2017 16:58:24] checking samtools version
[12/14/2017 16:58:24] samtools sort version is new
[12/14/2017 16:58:24] reading input files list
[12/14/2017 16:58:24] checking input files
[12/14/2017 16:58:24] generating tasks
[12/14/2017 16:58:24] generating tasks for NGMLR/Sniffles
Traceback (most recent call last):
  File "/home/nextsv/nextsv.py", line 998, in <module>
    main()
  File "/home/nextsv/nextsv.py", line 123, in main
    ngmlr_sniffles_tasks = generate_tasks_ngmlr_sniffles(settings)
  File "/home/nextsv/nextsv.py", line 702, in generate_tasks_ngmlr_sniffles
    align_bam_dir = os.path.join(out_dir, '1_align_bam')
  File "/usr/lib/python2.7/posixpath.py", line 70, in join
    elif path == '' or path.endswith('/'):
AttributeError: 'NoneType' object has no attribute 'endswith'
```

**Comment by fangli80** [comment]
Hi, 
Thanks for using NextSV. Can you please upload your config file?

**Comment by matbreno** [comment]
[1678_nextSV.config.zip](https://github.com/Nextomics/nextsv/files/1560021/1678_nextSV.config.zip)

Hi, 
here's the file

**Comment by fangli80** [comment]
The problem is fixed. Please clone the latest version of NextSV and try again.  If you still have the issue, please let me know.

**Comment by matbreno** [comment]
Hi,
now it works.
Thank you very much.

**Comment by fangli80** [comment]
You are welcome.
